### ISSUE TITLE
incorrect padding size in decrypt_encrypted_key_portion

### ISSUE THREAD

**Issue by yifanlu** [mitchellrj/python-pgp#2]
I think the code is supposed to add enough 00 so the data is padded to a block size.

https://github.com/mitchellrj/python-pgp/blob/master/pgp/packets/packets.py#L935-L936

```python
            padding = bytearray(
                [0x00] * (sym_block_size - len(encrypted_data) % sym_block_size))
```

**Comment by wdoekes** [comment]
Correct: I changed that too, here: https://github.com/mitchellrj/python-pgp/pull/11/files

**Comment by mitchellrj** [comment]
Closing in favour of #11.
